services:
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker-data/db:/custom/mount:/var/lib/postgresql/data
  goapp:
    build:
      context: ./
      dockerfile: goapp.Dockerfile
    tty: true
    stdin_open: true
    depends_on:
      - postgres
    volumes:
      - ./:/app
    environment:
      - DB_HOST=postgres
      - BASE_PATH=""
    ports:
      - 3000:3000
